### ISSUE TITLE
configure script is failing

### ISSUE THREAD

**Issue by iamazeem** [liquidaty/zsv#11]
**Description**

On Ubuntu 18.04 and 20.04 under `bash`, the `configure` script fails with these errors:

```shell
$ ./configure
./configure: 214: [: unexpected operator
./configure: 225: [: unexpected operator
./configure: 227: [[: not found
...
checking whether compiler accepts __builtin_expect(0,0)..../configure: 156: [: 1: unexpected operator
no
checking whether compiler accepts __builtin_expect_with_probability(0,0,0.5)..../configure: 156: [: 1: unexpected operator
no
creating ... ./configure: 492: cannot create : Directory nonexistent
```

As the `configure` script specifies `#!/bin/sh`, the `bash` things such as `[[ condition ]]`, and `==` are not supported.
The same behavior has also been observed in the GitHub Actions CI pipeline.
However, with `#!/bin/bash`, it works fine.

You might want to look into it on your side as well.
Maybe, a fix would be required either to use pure `sh` stuff or using `bash`

**Expected**

The `configure` script should work without fail.

**Actual**

The `configure` script fails with multiple syntax errors.

**Comment by liquidaty** [comment]
Thank you! Please let me know if this isn't resolved with 630d2de8316e0f3983b1f7f62f58e5f2126c8d47

**Comment by iamazeem** [comment]
You're welcome!
One error for `[[ ]]` is resolved but the others for `==` still persist:

```shell
$ ./configure
./configure: 214: [: unexpected operator
./configure: 225: [: build: unexpected operator
./configure: 227: [: build: unexpected operator
...
checking whether compiler accepts __builtin_expect(0,0)..../configure: 156: [: 1: unexpected operator
no
checking whether compiler accepts __builtin_expect_with_probability(0,0,0.5)..../configure: 156: [: 1: unexpected operator
no
creating ... ./configure: 492: cannot create : Directory nonexistent
```

**Comment by iamazeem** [comment]
Changing `==` to `=` works fine. Tested this on my side.

**Comment by liquidaty** [comment]
lmk if that change doesn't resolve

**Comment by iamazeem** [comment]
Working fine now. Thanks! :+1:
