### ISSUE TITLE
Segfault when calling zsv help select

### ISSUE THREAD

**Issue by Thernn88** [liquidaty/zsv#118]
Also get a segfault when calling zsv help echo.

Running .3.5 on 22.04 Ubuntu

**Comment by liquidaty** [comment]
Reproduced

**Comment by liquidaty** [comment]
Thank you for reporting this issue. It should be fixed with pull #119-- pls further comment if the issue persists

**Comment by liquidaty** [comment]
Actually, not quite fixed for `zsv help count`

**Comment by Thernn88** [comment]
Thank you for the quick fix. I'll let you know if I have further issues. Aside from zsv help count which you already found.

**Comment by liquidaty** [comment]
S/b complete now #120

**Comment by Thernn88** [comment]
Thank you!
