### ISSUE TITLE
make install fails for lib on Windows (MinGW + GitBash)

### ISSUE THREAD

**Issue by iamazeem** [liquidaty/zsv#12]
**Description**

`make install` fails for lib on Windows (MinGW + GitBash).

Errors:

```text
Working directory is 'D:\a\zsv\zsv'
[command]"C:\Program Files\Git\bin\git.exe" version
git version 2.35.1.windows.2
...
./configure --prefix=build
make install
...
Building with mingw
mingw32-make[1]: Entering directory 'D:/a/zsv/zsv/src'
Using config file /d/a/zsv/zsv/config.mk
No profiling set. To use PGO, compile with PGO=1, then run with data, then compile again with PGO=2
No VECTOR_SIZE set, using 256
Makefile:13: /d/a/zsv/zsv/config.mk: No such file or directory
mingw32-make[1]: Leaving directory 'D:/a/zsv/zsv/src'
mingw32-make[1]: *** No rule to make target '/d/a/zsv/zsv/config.mk'.  Stop.
mingw32-make: *** [Makefile:54: install] Error 2
```

Some digging into it revealed that `src/Makefile:147` was unable to create a target for `LIBZSV_INSTALL` which contains `/d/a/zsv/zsv/config.mk`.

Could you please share your Windows + MinGW environment specs with versions?

**Expected**

The build should be successful.

**Actual**

The build is failing.

**Comment by liquidaty** [comment]
we're using osx + mingw to build, probably different from your runner.

Can you check if your runner environment has the `realpath` command? if not that would be the culprit

**Comment by iamazeem** [comment]
So, you're cross-compiling. :+1: 
And, what about BSD?

**Comment by liquidaty** [comment]
Yea, cross compiling with osx/mingw64 for Win, but using native AMI for FreeBSD

**Comment by iamazeem** [comment]
Right. FreeBSD and GCC versions?

**Comment by iamazeem** [comment]
On FreeBSD 13.0-RELEASE, the build is failing with these `make` errors:

```text
make: stopped in /Users/runner/work/zsv/zsv
make: "/Users/runner/work/zsv/zsv/Makefile" line 11: Need an operator
make: "/Users/runner/work/zsv/zsv/Makefile" line 12: Missing dependency operator
make: "/Users/runner/work/zsv/zsv/Makefile" line 13: Need an operator
```

Tried `gmake` also but it generated more errors similar to above.

Applied some changes as discussed [here](http://alfix.gitlab.io/bsd/gnu/coding/2017/01/28/gnu-make-vs-bsd-make.html) but the build was still failing.

Could you please verify the `make` type/version on your FreeBSD and whether it's still building and does not produce above errors?

**Comment by liquidaty** [comment]
Ah, I know the issue, which is that on BSD we have aliased `make` to `gmake`, so whenever make then calls another `make` it's actually calling `gmake` (version 4.3). Will update so that the alias is not needed

**Comment by liquidaty** [comment]
lmk if that didn't fix!
