### ISSUE TITLE
`zsv sql` returns exit code 0 for missing CLI args

### ISSUE THREAD

**Issue by iamazeem** [liquidaty/zsv#160]
**Environment**

- Ubuntu 22.04 LTS
- zsv 0.3.8-alpha

**Description**

Unlike `stack`, `compare` and other similar commands that return exit code 1 after printing their help text, `sql` command does not:

```shell
$ zsv stack > /dev/null; echo $?
1

$ zsv compare > /dev/null; echo $?
1

$ zsv sql > /dev/null; echo $?
0
```

**Comment by liquidaty** [comment]
#164
