### ISSUE TITLE
[QA] Test AMD64 Linux/gcc and Linux/clang RPM packages #18

### ISSUE THREAD

**Issue by iamazeem** [liquidaty/zsv#19]
Please download and install RPM packages on your side.

Download Linux/gcc and Linux/clang RPM packages from here:
https://github.com/liquidaty/zsv/actions/runs/2438944223

After downloading and extracting `zsv-amd64-linux-gcc.deb`:

Install:

```shell
sudo yum install ./zsv-amd64-linux-gcc.rpm
```

Play around with the installed `zsv` to make sure it's working.

Uninstall:

```shell
sudo yum remove zsv
```

After Linux/gcc, please test `zsv-amd64-linux-clang.rpm` also.

---

During my testing, I found out that `zsv` has a transitive dependency on `libtinfo5`. (Built on Ubuntu 18.04 with `rpmbuild`)
I had to install it separately on Ubuntu 18.04 with `apt`.
For my testing, I used `alien` to install the RPM package on Ubuntu 18.04 and 20.04.
Besides, there's no explicit linking with this library (`libtinfo`) in the source code.
If you have knowledge about this, please do share. Thanks!

---

In addition, earlier on May 23rd, I had this output for `ldd` command without `libtinfo`:

```shell
$ ldd ./build/Linux/rel/cc/bin/cli
    linux-vdso.so.1 (0x00007ffeb8beb000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f09a3794000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f09a378d000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f09a35a1000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f09a3953000)
```

But, now I'm getting this output with `libtinfo`:

```shell
$ ldd ./build/Linux/rel/gcc/bin/cli 
    linux-vdso.so.1 (0x00007ffc0c9f4000)
    libtinfo.so.6 => /lib/x86_64-linux-gnu/libtinfo.so.6 (0x00007f34e6ade000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f34e6abc000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f34e6ab5000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f34e68c9000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f34e6cab000)
```

On Ubuntu 18.04, it's `libtinfo.so.5`.
On Ubuntu 20.04, it's `libtinfo.so.6`.

We need to determine the cause of this addition and possibly remove this dependency.
Otherwise, this will indirectly be affecting the packaging and we'll have to ship this as part of the package.

**Comment by iamazeem** [comment]
`libtinfo` issue has been resolved with `--disable-termcap` flag.
Added via commit https://github.com/liquidaty/zsv/commit/3543a8a2b8b45674880054a448658f24907029c5 and tested on vanilla Ubuntu 18.04 where `libtinfo` was not present.

**Comment by liquidaty** [comment]
Tested zsv-amd64-linux-gcc.rpm and zsv-amd64-linux-clang.rpm. all good!

**Comment by iamazeem** [comment]
@liquidaty: Thank you for verifying! Closing it as done. 👍🎉🤓
