### ISSUE TITLE
sheet: running via ssh to windows (2016 server) fails

### ISSUE THREAD

**Issue by liquidaty** [liquidaty/zsv#234]
ssh'ing into a windows box and then running `zsv.exe sheet` fails

however, RDP'ing into the windows machine, opening cmd.exe and running `zsv.exe sheet` works

**Comment by iamazeem** [comment]
@liquidaty: **UPDATE**
After SSHing into the Windows box, under `cmd` (Command Prompt), setting the `TERM` env var to empty works for me:

```cmd
set TERM=
zsv_sheet.exe test.csv
```

Demo:

![zsv-sheet-win10-ssh-demo](https://github.com/user-attachments/assets/2278efe8-57e0-4eef-8e1b-f23b034bc848)

**Comment by iamazeem** [comment]
Unsetting the `TERM` env var in the code works fine as well.

`app/sheet.c` in main function:

```c
#if defined(WIN32) || defined(_WIN32)
  if (setenv("TERM", "", 1) != 0) {
    fprintf(stderr, "Unable to unset TERM env var\n");
  }
#endif
```

No need to manually unset `TERM` env var for `ssh`/`wine`/`cmd`/`powershell`.

Demo:

![zsv-sheet-win10-ssh-demo-2](https://github.com/user-attachments/assets/00f13dd5-a240-46b0-8ec0-a21b981cab1f)

**Comment by liquidaty** [comment]
What ssh client are you using? I'm unable to replicate with MacOS native terminal + windows native ssh service

**Comment by iamazeem** [comment]
**Windows 10**: OpenSSH Server (enabled from options)
**Ubuntu 22.04**: OpenSSH Client (`OpenSSH_8.9p1 Ubuntu-3ubuntu0.10, OpenSSL 3.0.2 15 Mar 2022`)

**Comment by iamazeem** [comment]
Is it failing with an error?
What's the exact behavior?
A demo GIF would be helpful.

**Comment by liquidaty** [comment]
Issue occurs on Server 2016; confirmed this issue does not occur on more recent versions of Windows e.g. 10 and Datacenter 2022. Will not fix.
