### ISSUE TITLE
optimize data sizes

### ISSUE THREAD

**Issue by matu3ba** [liquidaty/zsv#3]
zsv_scanner, zsv_ctx, zsv_stack_colname etc look like they have padding, since the `char`, `bool` fields etc are not at the end of struct.

C is not allowed to reorder fields, so there might be significant padding. Consider reordering the struct fields.

**Comment by liquidaty** [comment]
Will do

**Comment by liquidaty** [comment]
There is a counterargument that the layout of the structure could have a performance impact that outweighs the impact of padding. Not sure which would win, or if either would be measurable/material, so we're going to hold off on this pending benchmark evidence in support
