### ISSUE TITLE
Playground fails on iPhone 

### ISSUE THREAD

**Issue by liquidaty** [liquidaty/zsv#313]
![DE2E39FF-52C2-4A61-BB3E-FA9853EB0617](https://github.com/user-attachments/assets/c4dfabc1-5cac-42eb-8483-82faa5c90135)

**Comment by iamazeem** [comment]
Looked into it a bit.
The opcode 253 (0xFD) refers to SIMD instructions.

References:
- https://webassembly.github.io/spec/core/binary/instructions.html#vector-instructions
- https://webassembly.github.io/spec/core/syntax/instructions.html#vector-instructions
- https://pengowray.github.io/wasm-ops/.

The wasm playground is built with `-msse2 -msimd128` flags.
The above error indicates the absence of SIMD instructions.

Analyzed the generated wasm for opcode 0xFD with `wasm-objdump` and the output is attached below:

```shell
$ wasm-objdump -d cli.em.wasm | grep ': fd ' > cli.em.wasm.fd-253.txt
```

Output: [cli.em.wasm.fd-253.txt](https://github.com/user-attachments/files/17964427/cli.em.wasm.fd-253.txt)

Observe opcode prefixes `v128`, `i8x16`, `i32x4`, etc.

To verify, the playground may be built without `-msse2 -msimd128` flags and tested on iPhone.

**Comment by liquidaty** [comment]
We have solved this elsewhere. I will add some details

**Comment by liquidaty** [comment]
@iamazeem confirmed that our solution was just to remove those flags; we also had to change from -O3 to -O2 but that might have been for reasons unrelated to what is required here. In addition, due to the performance difference we used two versions-- one for non-IOS and another for iOS-- and used a proxy to choose which version to serve. It might be worth benchmarking the difference in performance on non-IOS, between the optimized and generic versions, to decide whether it's worth trying that two-version approach versus just having a single version that works on all.

**Comment by iamazeem** [comment]
@liquidaty: Please test https://liquidaty.github.io/zsv/ on iPhone again. Thanks!

**Comment by iamazeem** [comment]
Fixed with https://github.com/liquidaty/zsv/commit/bdee8d2e04436ff06964c1cda064bff07baa68a2.

**Comment by iamazeem** [comment]
Should the ASCII art be removed? :thinking: 
It's not displayed properly on smaller screens.

**Comment by liquidaty** [comment]
ASCII art looks good to me. Keep it!

**Comment by iamazeem** [comment]
@liquidaty: Added a wiki page for the  playground.
See https://github.com/liquidaty/zsv/wiki/zsv-playground.
Please review and update as needed. Thanks!
