### ISSUE TITLE
extension transformation example misbehaves

### ISSUE THREAD

**Issue by liquidaty** [liquidaty/zsv#345]
Not quite sure how it passes CI. Trying to manually run test-sheet-extension-2 from ext_example/Makefile, the cursor no longer can be moved down using down arrow or G after the custom transformation (T) command is entered. Possibly this issue has existed for some time now and is somehow slipping through CI. Will update with last good commit. @richiejp

**Comment by liquidaty** [comment]
Last good commit: abf0407fdd3751ed31f2edc59b0b8aec67f7f4ed

**Comment by liquidaty** [comment]
Thanks @richiejp. Will respond do your questions in a separate comment.

Here are specific instructions to reproduce (on my machine), where commands are prefixed by `> `. Are you able to reproduce on yours?
```
> make clean
> rm -rf build
> ./configure
> make install
Built /.../zsv/build/.../bin/cli
cp -p /.../zsv/build/.../bin/cli /usr/local/bin/zsv

> cd app/ext_example
> ./configure
> make
...
Built /.../zsv/build/.../bin/zsvextmy.so
Built /.../zsv/build/.../bin/zsvextmysheet.so

> /.../zsv/build/.../bin/cli register mysheet
Loaded zsvextmysheet.so from /.../zsv/build/.../bin/zsvextmysheet.so
Loaded extension zsvextmysheet.so
Extension mysheet registered
Exiting mysheet extension example!

> make -C ../test worldcitiespop_mil.csv
...

>/.../build/.../bin/cli sheet ../test/worldcitiespop_mil.csv
```
Then type "T", which will invoke the extension's `my_transformation_command_handler`

Then try to move the cursor down past row 2-- it fails.

**Comment by liquidaty** [comment]
@richiejp see https://github.com/liquidaty/zsv/pull/349

**Comment by liquidaty** [comment]
@richiejp this was due to a stale libzsvutil.a on my end! Will consider updating the build process to detect this massive waste of time. Still, there are several refactors that should be addressed:

- consolidation of index.c vs transformation.c
- remove the changes that were made to libzsvutil.a writer dependency on zsv_index_add_row(); make it a generic pointer instead and optimize + benchmark for performance since this is a seldom-used branch

**Comment by richiejp** [comment]
> @richiejp this was due to a stale libzsvutil.a on my end! 

@liquidaty  I've hit similar issues. I see you set the target to `.PHONY`. Another way is that most of the rules could be refactored into a single Makefile which is then included in the app/Makefile, app/test/Makefile etc. This way the original rules would be used.

Also in a similar vein I added the sheet folder source files as dependencies in this PR: https://github.com/liquidaty/zsv/pull/336/files#diff-0c6c7defde945725f3d878fe20d0866dc29520f5f3816ff91ca56df2211e5451R208

**Comment by liquidaty** [comment]
Closing this for now, let's keep you suggestions in mind for a separate issue
