### ISSUE TITLE
"Illegal instruction" when running on Intel Ivy Bridge CPU

### ISSUE THREAD

**Issue by dbro** [liquidaty/zsv#41]
Hello- I wanted to compare the speed benchmark for zsv with [csvquote](https://github.com/dbro/csvquote), and ran into this issue where zsv appears to not run on my 2012-era CPU. This is likely because my CPU does not support the AVX2 set of SIMD instructions.

```
$ ./confgiure
$ sudo make install
$ zsv count testdata.csv
Illegal instruction
```

For the zsv benchmark, I think you may want to use a different test data set instead of [https://burntsushi.net/stuff/worldcitiespop_mil.csv](https://burntsushi.net/stuff/worldcitiespop_mil.csv) because that data does exercise any special csv parsing capabilities. With this data set, to perform the benchmark tests to count rows and select columns the standard unix text processing tools wc and cut would suffice (or awk).

A better test for benchmarking would be a large file (multiple GB) that contains quoted fields with embedded field separators and record separators (commas and newlines). A clever example of a self-generating CSV test file is [here](https://github.com/skeeto/scratch/blob/master/csvquote/etc/csvdump.c) which provides an infinite stream of random CSV data that can be adjusted to increase or decrease the portion of quoted fields that contain separator characters that should be treated as data.

Also the benchmark test should check for correct results as well as measure speed.

Hope these suggestions are helpful.
Dan

**Comment by liquidaty** [comment]
Thank you, will review. The worldcitiespop_mil.csv file does have a few special cases but admittedly, not many. Will look into the generator and adding a check for correctness. Re the illegal instruction, would you have any suggestion as to how to replicate (without having to go buy an old computer with that chip)? Happy to look into it if we can replicate, or take a patch if anyone else can provide.

**Comment by dbro** [comment]
Hi- I think it might be possible to simulate the limitations of older processors by changing some of the compiler flags. I am only guessing here, but removing some of compiler flags [here](https://github.com/liquidaty/zsv/blob/406241ca78bb5ac6a8fe1b81e700150b52c92a84/configure#L480) and avoiding the SIMD function (referred to on line 512 in the same file) called _mm256_movemask_epi8 which depends on AVX2 support.
Dan

**Comment by dbro** [comment]
Sure. I needed to add a ".txt" to config.mk for github to accept it as an attachment.

[config.log](https://github.com/liquidaty/zsv/files/8973280/config.log)
[config.mk.txt](https://github.com/liquidaty/zsv/files/8973283/config.mk.txt)

**Comment by liquidaty** [comment]
Thank you. To confirm that `_mm256_movemask_epi8` is indeed the culprit, would you mind to modify your zsv/config.mk file to remove `-DHAVE__MM256_MOVEMASK_EPI8` from CFLAGS_AUTO, and then run `make clean test install` and let me know the result?

**Comment by dbro** [comment]
I see two errors when running that:

```
gcc -pipe -ffunction-sections -fdata-sections -fpic -std=gnu11 -O3 -DNDEBUG -Wno-gnu-statement-expression -Wshadow -Wall -Wextra -Wno-missing-braces -pedantic -DSTDC_HEADERS -D_GNU_SOURCE -ftree-vectorize -fvisibility=hidden -I/usr/local/include -mavx2 -DZSV_EXTRAS -DNO_MEMMEM -DHAVE_IMMINTRIN_H -DHAVE_TGETENT -DHAVE___BUILTIN_EXPECT -DHAVE___BUILTIN_EXPECT_WITH_PROBABILITY -flto -Iexternal/utf8proc-2.6.1 -DUTF8PROC -DUTF8PROC_STATIC -I/home/dan/src/zsv/include -Iexternal/utf8proc-2.6.1 -DINCLUDE_SRC -o /home/dan/src/zsv/build/Linux/rel/gcc/objs/utils/memmem.o -c utils/memmem.c 
utils/memmem.c: In function ‘twoway_memmem’:
utils/memmem.c:86:11: warning: comparison of integer expressions of different signedness: ‘long int’ and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
   86 |   if (z-h < l) return 0;
      |           ^
utils/memmem.c: At top level:
cc1: note: unrecognized command-line option ‘-Wno-gnu-statement-expression’ may have been intended to silence earlier diagnostics
```
and
```
make[3]: Leaving directory '/home/dan/src/zsv/app'
test-echo: 
Illegal instruction
make[2]: *** [Makefile:109: test-echo] Error 132
make[2]: Leaving directory '/home/dan/src/zsv/app/test'
make[1]: *** [Makefile:345: test] Error 2
make[1]: Leaving directory '/home/dan/src/zsv/app'
make: *** [Makefile:57: test] Error 2
```

**Comment by liquidaty** [comment]
Thank you. Back to the drawing board. Could you send your exact CPU model etc?

**Comment by liquidaty** [comment]
Actually, forgot one more thing-- would you mind to try:
```
./configure CFLAGS=-march=native && make clean test install
```
?

**Comment by dbro** [comment]
Same result.
[config.mk.txt](https://github.com/liquidaty/zsv/files/8973836/config.mk.txt)
[config.mk.log](https://github.com/liquidaty/zsv/files/8973838/config.mk.log)

**Comment by dbro** [comment]
```
$ cat /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
stepping	: 9
microcode	: 0x21
cpu MHz		: 1664.628
cache size	: 6144 KB
physical id	: 0
siblings	: 8
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d
vmx flags	: vnmi preemption_timer invvpid ept_x_only flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit srbds
bogomips	: 5187.98
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

```

**Comment by liquidaty** [comment]
Thank you. Only remaining thing I can think of, without being able to replicate here, is to comment out CFLAGS_AUTO entirely from config.mk and then `make clean install`. If you have a chance, could you try that?

**Comment by dbro** [comment]
I got the same result with that change.

I removed/disabled some other CFLAGS and that seems to have got it to compile successfully with "sudo make install". See the attached config.mk(.txt) 

I got some errors when running "sudo make test" so I also installed the debian packages jq and libjq-dev and ran ldconfig. The "sudo make test" command eventually generates these errors:

/usr/bin/ld: /tmp/zsv_jq.Sz6UBU.ltrans0.ltrans.o: in function `jv_to_json_func':
<artificial>:(.text.jv_to_json_func+0x1b): undefined reference to `jv_dump_string'
/usr/bin/ld: <artificial>:(.text.jv_to_json_func+0x2c): undefined reference to `jv_string_value'
[config.mk.txt](https://github.com/liquidaty/zsv/files/8980158/config.mk.txt)

... and many similar lines

But that might not be relevant for what I'm trying to do: test the benchmarks. Before these errors happened it downloaded the large CSV test file from the xsv repo. And the cli binary runs and can count the lines in that file ("./build/Linux/rel/gcc/bin/cli count -i app/test/worldcitiespop_mil.csv"). Here are the results for the benchmarks comparing zsv and csvquote:

**_count_**

$ time ./build/Linux/rel/gcc/bin/cli count -i app/test/worldcitiespop_mil.csv 
1000000

real	0m0.252s
user	0m0.240s
sys	0m0.012s

$ time ../csvquote/csvquote app/test/worldcitiespop_mil.csv | wc -l
1000001

real	0m0.029s
user	0m0.021s
sys	0m0.034s

**_tsv_**

$ time ./build/Linux/rel/gcc/bin/cli 2tsv app/test/worldcitiespop_mil.csv > /dev/null

real	0m0.339s
user	0m0.331s
sys	0m0.008s

$ time ../csvquote/csvquote app/test/worldcitiespop_mil.csv | ../csvquote/csvquote -u -t > /dev/null

real	0m0.024s
user	0m0.009s
sys	0m0.037s

**_select_**

$ time ./build/Linux/rel/gcc/bin/cli select app/test/worldcitiespop_mil.csv -W -n -- 2 1 3-7 > /dev/null

real	0m0.356s
user	0m0.352s
sys	0m0.004s

$ time ../csvquote/csvquote app/test/worldcitiespop_mil.csv | cut -d',' -f 2,1,3-7 | ../csvquote/csvquote -u > /dev/null

real	0m0.280s
user	0m0.255s
sys	0m0.112s

however, because it's using cut the order of the columns will not be shuffled as requested. A slower and correct version using mawk:
$ time ../csvquote/csvquote app/test/worldcitiespop_mil.csv | mawk -F',' '(1) {print $2,$1,$3,$4,$5,$6,$7}' | ../csvquote/csvquote -u > /dev/null

real	0m0.506s
user	0m0.482s
sys	0m0.104s

**Comment by dbro** [comment]
Also you may want to look at some of the SIMD methods for parsing CSV described here: https://news.ycombinator.com/item?id=29439403

**Comment by liquidaty** [comment]
Thank you. Could you send me the config.mk you ended up using, that worked for select and count?

Thanks for the benchmarks. It's very cool that your lib is super concise and clean in under 200 lines of code. As for performance, it seems reasonable that it is faster because, if I'm understanding correctly, it's a little bit of apples vs oranges. I'm guessing the difference is mainly attibutable to edge cases that `zsv` performance takes a hit for to achieve one of its primary objectives to handle real-world data in a manner consistent with Excel.

For example, I can create "malformed.csv" as follows:
```
echo 'abc"def,ghi"jkl' > malformed.csv
```

which looks like this in Excel:

<img width="131" alt="image" src="https://user-images.githubusercontent.com/26302468/175663987-f9c4460e-3bf3-4975-8d00-8825c78f1eb5.png">

and which `zsv` and `xsv` will treat in the same way as Excel:
``` shell
# both of the below will output "abc""def","ghi""jkl"
echo 'abc"def,ghi"jkl' | zsv select
echo 'abc"def,ghi"jkl' | xsv select -- 1,2
```

but which csvquote treats as a single cell, removes the comma, and outputs what one might consider to be non-normalized CSV:
```
abc"defghi"jkl
```

which is neither "normalized" nor consistent with Excel handling.

I understand these edge cases are rare, but I have seen them many times "in the wild" and as a practical matters, users are much more willing to accept Excel as correct, and then be willing to fix their data, then they are to accept that their data is malformed if Excel would agree with them.

Re the link re https://news.ycombinator.com/item?id=29439403, there are several comments that also point out that some of the generalized "we could just do this for CSV" statements are overly simplistic; we looked a lot at LeMire and Langdale's work while building zsv and with all due respect to the awesome SIMD work they have done, we are also of the view that the "csv is as easy as JSON" view is inaccurate-- or at least, certainly for meeting one of `zsv`s primary objectives which is to treat all CSV input, including edge cases, in a manner consistent with Excel.

Without having to handle these kind of cases, a DFA can be faster than `zsv`, at least for certain operations; another example I've seen which csvquote reminds me of is https://github.com/c-blake/nio. The inefficiency is not only attributable to the parsing side, but also on the "normalization" side: output no longer is guaranteed to fit within the input buffer, which means that input and output buffer cannot be blankly assumed to be shared. In other words, given the input `abc"def`, we don't want to just output the same thing because that would be malformed in / malformed out. Instead, we want to normalize it to `"abc""def"`.

Lastly, although it is not listed as a core objective of `zsv` (perhaps it should be), parsing on solely a cell-by-cell basis is significant limiting for even simple operations such as re-ordering columns, and in our view makes the library less re-usable because is it common to want process at a row level (such as simply to output the entire row only if column 5 contains X), and having the parser do that for you efficiently is a net positive to end performance.

Still want to look into why the build process wasn't working...

**Comment by dbro** [comment]
Hi, sure here is the config file:
[config.mk.txt](https://github.com/liquidaty/zsv/files/8984005/config.mk.txt)

Thanks for clarifying. I am not familiar with abnormal quoting behavior. I assume that means data that does not conform with [RFC 4180](https://datatracker.ietf.org/doc/html/rfc4180). How common is that, and which applications produce data that does not conform? I have been using csvquote with real data for almost ten years and have not needed this so far. To be fair, csvquote may not be the right choice for people who work with data in Excel; it shines when working with amounts of data that are far larger than Excel can handle, and where speed and automation are more important.

You're correct in showing that csvquote does not attempt to repair csv input that does not conform to RFC 4180. If that is an important use case for zsv, I recommend you include it in the benchmark suite and provide some test cases that demonstrate what kinds of repairs are possible. What command did you to invoke csvquote? It might have been only the first "sanitization" stage, without the required "restore" stage. This demonstrates the difference:

```
$ echo 'abc"def,ghi"jkl' | ../csvquote/csvquote 
abc"defghi"jkl

$ echo 'abc"def,ghi"jkl' | ../csvquote/csvquote | ../csvquote/csvquote -u
abc"def,ghi"jkl

$ echo 'abc"def,ghi"jkl' | ../csvquote/csvquote | xxd -g 1 -c 20
00000000: 61 62 63 22 64 65 66 1f 67 68 69 22 6a 6b 6c 0a              abc"def.ghi"jkl.
``` 
Note the non-printing characters represented by dots in the output from xxd. When sanitizing, csv replaces embedded commas and newlines with nonprinting characters (this is replacement, not removal). When used with both stages, csvquote will restore the original data when asked - even if the original data does not conform to RFC 4180.

To try and benchmark on a more up to date CPU, here are some results comparing zsv and csvquote when running on a Google cloud instance (AMD EPYC 7B12 which supports AVX2). As before, the times for the "select" benchmark are faster for zsv but otherwise slower.

```
$ time zsv count -i worldcitiespop_mil.csv
1000000         
                
real    0m0.070s
user    0m0.062s                                                                                              
sys     0m0.008s

$ time ./csvquote worldcitiespop_mil.csv | wc -l1000001                         real    0m0.041s                                                                                              
user    0m0.023s
sys     0m0.028s

$ time zsv 2tsv worldcitiespop_mil.csv > /dev/null
                
real    0m0.220s
user    0m0.207s
sys     0m0.012s                                                                                              

$ time ./csvquote worldcitiespop_mil.csv | ./csvquote -u -t > /dev/null

real    0m0.020s
user    0m0.000s
sys     0m0.036s

$ time zsv select worldcitiespop_mil.csv -W -n -- 2 1 3-7 > /dev/null          

real    0m0.198suser    0m0.198s
sys     0m0.000s

$ time ./csvquote worldcitiespop_mil.csv | cut -d',' -f2,1,3-7 > /dev/null

real    0m0.408s
user    0m0.345s
sys     0m0.117s

$ time ./csvquote worldcitiespop_mil.csv | mawk -F',' '(1) {print $2,$1,$3,$4,$5,$6,$7}' > /dev/null

real    0m0.878s
user    0m0.845s
sys     0m0.033s
```

**Comment by liquidaty** [comment]
Thanks-- super impressive performance. I don't seem to be able to replicate though-- my output is still comma-delimited:
```
./csvquote < worldcitiespop_mil.csv | ./csvquote -u -t
```
outputs:
```
Country,City,AccentCity,Region,Population,Latitude,Longitude
ir,sarmaj-e hoseynkhani,Sarmaj-e Hoseynkhani,13,,34.3578,47.5207
ad,aixirivali,Aixirivali,06,,42.4666667,1.5
...
```
Running on MacOS 10.15, built with `make` and clang. Any suggestions?

As for the edge cases, they are from real-world occurrences of others running on data that also is too big for Excel, but often likely gone through multiple corporate merger/acquisitions, and often in multinational corporations that had over time migrated data not only across database / vendor / other, but also between countries and languages and encodings etc (including codepage-based / non-unicode multi-byte etc). TBH `select` is a much more important command than count, for our purposes, but if your benchmarks are representative, it might be worth taking a closer look at using a "fast lane" for non-edge-case data...

**Comment by dbro** [comment]
Good catch, thanks. csvquote probably is not a good option for transforming csv to tsv. The reason why is that in the original csv version of the file, fields with embedded commas would be quoted and fields with embedded tabs would not be quoted. In the transformed tsv version, the fields with embedded tabs would now need to be quoted, which would require characters to be inserted into the file - that is not something that csvquote will do. Here is an example of a data file that would not work with a csvquote transform:

```
field1,"field 2 , has a comma in it",field 3 has a \t tab in it,field4
```
Two correct transformations to tsv are then:
```
field1\tfield 2 , has a comma in it\t"field 3 has a \t tab in it"\tfield4
field1\t"field 2 , has a comma in it"\t"field 3 has a \t tab in it"\tfield4
```
Neither csvquote nor the unix command tr would be able to insert the quotes around field 3.

Note that if you're looking for examples of fast code and can assume AVX2 support, then [skeeto's rewrite of csvquote](https://github.com/skeeto/scratch/tree/master/csvquote) will be faster than the version in the repository I maintain. After exploring the subject, I decided against adding explicit SIMD instructions in the csvquote code because I didn't like the extra complexity and effort to maintain it. I found most of the speed gains come from using SIMD to search for quote characters, and that the string library function memchr() will use SIMD on systems that support it. With typical multi-stage pipelines, I expect that csvquote will not be the slowest link and additional speed gains won't impact overall run time.

**Comment by liquidaty** [comment]
Have reproduced the error on older hardware. Can't rely on __AVX2__ macro, need a better configure test for _mm256_movemask_epi8

**Comment by liquidaty** [comment]
@dbro better late than never? Think this is good to go now. If you've time to try it out, please do and lmk how it goes

**Comment by liquidaty** [comment]
Resolved
