### ISSUE TITLE
Add version.h to store the released version

### ISSUE THREAD

**Issue by iamazeem** [liquidaty/zsv#87]
Currently, there's no version file in the codebase.
The version is extracted using `git` command and used as a compile time macro `VERSION` wherever needed.
Also, the CI workflow is being updated with the historical released version. See: 
https://github.com/liquidaty/zsv/blob/dab4873f1731bb3ebbf847e61e5c4b2da365dd85/.github/workflows/ci.yml#L26

Instead of hardcoding the released version as `TAG` in the CI, it is suggested to use a `version.h` header file as the default place to store version information e.g. version, branch, date, etc.

**Comment by iamazeem** [comment]
Template for `version.h` header file:

```c
// THIS FILE IS AUTOMATICALLY GENERATED/UPDATED DURING BUILD.
// DO NOT EDIT THIS MANUALLY UNLESS YOU KNOW WHAT YOU'RE DOING!

#ifndef __VERSION_H__
#define __VERSION_H__

#define VERSION "x.y.z"

#endif // __VERSION_H__

// Could be more macros if required e.g. BRANCH, BUILD_TYPE, etc.
```

`#pragma once` may be used instead of header guards if all the targeted compilers support it i.e.:

```c
// THIS FILE IS AUTOMATICALLY GENERATED/UPDATED DURING BUILD.
// DO NOT EDIT THIS MANUALLY UNLESS YOU KNOW WHAT YOU'RE DOING!

#pragma once

#define VERSION "x.y.z"
```

**Comment by liquidaty** [comment]
OK. Using this approach, how would the ci.yml script assign a value to TAG, if it isn't hardcoded?

**Comment by iamazeem** [comment]
Read the version from the `version.h` and set it as an env var in a separate step.
The subsequent steps will use this value.

The existing version itself would be used for a PR or direct commit.
For a new tag/release, the `version.h` will be updated, committed back to repo, and this version would be used.

**Comment by iamazeem** [comment]
Reopening. See https://github.com/liquidaty/zsv/issues/438#issuecomment-3918997536 for details.
