### ISSUE TITLE
Incorrect columns for last row

### ISSUE THREAD

**Issue by woollybah** [liquidaty/zsv#88]
A user reported that the last row of some data was showing the incorrect number of columns.
I tested the file with both the `pull` and `simple` examples, and it shows the same problem in both.

Here's a version of the data exhibiting the issue. Most text has been converted to underscores.
The file is semi-colon (`;`) delimited, is UTF-8 encoded, and has some non-ascii characters :

[wrong_cols.csv](https://github.com/liquidaty/zsv/files/10180922/wrong_cols.csv)

The last row reports 46 columns instead of 37.

Adding a single character to one of the preceding rows (from row 396 onwards) results in a successful parse.
Pulling the header and last row into a new file results in a successful parse.

Tested on Windows (x64) and macOS (arm64).

**Comment by liquidaty** [comment]
Also, the `pull` and `simple` examples do not demonstrate how to use the library options to specify a delimiter other than comma (unlike the full `zsv` CLI which supports that with the `-O` option). Did you modify the examples to account for using a semicolon delimiter and if so could you describe the code modifications used for that?

**Comment by woollybah** [comment]
Sorry. I made a change to those examples, adding the following to `opts` :
```
  opts.delimiter = ';';
```

This is the end of the run (same for both `pull` and `simple`) against the csv I posted above :
```
...
Row 520 has 37 columns of which 23 are non-blank
Row 521 has 37 columns of which 25 are non-blank
Row 522 has 37 columns of which 25 are non-blank
Row 523 has 37 columns of which 30 are non-blank
Row 524 has 37 columns of which 27 are non-blank
Row 525 has 37 columns of which 30 are non-blank
Row 526 has 37 columns of which 32 are non-blank
Row 527 has 37 columns of which 31 are non-blank
Row 528 has 46 columns of which 37 are non-blank
```
As you can see, the last row appears to have 46 columns, according to the library.

I will take a look at trying out the `zsv` tool, with specific options. Thanks

**Comment by woollybah** [comment]
Using the cli `serialize` command, shows the issue. The last 5 columns of the last row should be empty. It appears to be offset to the right by 9 columns.

```
> cli serialize -O ";" wrong_cols.csv
```

The last 10 columns :
```
__-_____,ZOOM_IMG_1,____
__-_____,ZOOM_IMG_2,__________ä__å_______________________
__-_____,ZOOM_IMG_3,__
__-_____,ZOOM_IMG_4,_.__
__-_____,ZOOM_IMG_5,__.__
__-_____,ZOOM_IMG_6,_.___
__-_____,ZOOM_IMG_7,__.__
__-_____,ZOOM_IMG_8,__.__
__-_____,ZOOM_IMG_9,______//___.______________.__/___/______/________/__-_____.___?_=__________
__-_____,ZOOM_IMG_10,______//___.______________.__/______/________/____/__-_______.___?_=__________
```
The cell value for `ZOOM_IMG_9` should appear in `ZOOM_IMG_1`, and the last 5 cells should be empty. The output of this command looks fine for all rows other than the last one.

**Comment by liquidaty** [comment]
This should now be resolved with the changes in branch csv-pending-bug-fix (https://github.com/liquidaty/zsv/tree/csv-pending-bug-fix). Could you please try it out and confirm?

**Comment by woollybah** [comment]
Good job!
The file appears to be parsing correctly now with the latest changes.

Thank you.

**Comment by liquidaty** [comment]
Great! This has been merged. Thank you for reporting this issue.
