### ISSUE TITLE
[Ubuntu 18.04] zsv linked GLIBC version issue

### ISSUE THREAD

**Issue by iamazeem** [liquidaty/zsv#90]
`zsv` did not work after installing the `.deb` packages.

Environment:

```shell
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```

Downloaded and tested with:

- https://github.com/liquidaty/zsv/releases/download/v0.3.4-alpha/zsv-0.3.4-alpha-amd64-linux-gcc.deb
- https://github.com/liquidaty/zsv/releases/download/v0.3.4-alpha/zsv-0.3.4-alpha-amd64-linux-clang.deb

Error:

```shell
$ zsv version
zsv: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by zsv)
zsv: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by zsv)
```

Linked libraries:

```shell
$ ldd $(which zsv)
/usr/bin/zsv: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/bin/zsv)
/usr/bin/zsv: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/bin/zsv)
	linux-vdso.so.1 (0x00007ffe0ffed000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd781c9a000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd781a96000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd7816f8000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd781307000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd781eb9000)
```

As these binaries are built on [Ubuntu 20.04](https://github.com/liquidaty/zsv/blob/78eefd87967a8b2f90ec857ee0aa961cb90d7149/.github/workflows/ci.yml#L21) so this issue is expected for the versions lower than 20.04 (where GLIBC version is not supported).

To support Ubuntu 18.04, the runner should be the same.
However, the [Ubuntu 18.04 runner has been deprecated](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/).

One solution could be to **generate a statically linked binary** to resolve this issue.
Another could be to build binaries on Docker containers and distribute those.

In addition, the minimum supported version of the target OS for the prebuilt binaries should properly be documented in the README in case the static linkage is not possible.

Thanks!

**Comment by liquidaty** [comment]
Thank you. I think we should make it a static build. Could you make those changes?

**Comment by iamazeem** [comment]
Sure, I'll try to generate static builds for the supported Linux variants.

However, it might not be possible for macOS, and we'll have to resort to `-mmacosx-version-min` compiler flag to specify the lowest supported version e.g. `-mmacosx-version-min=10.15`, if it comes to that. :thinking:

**Comment by iamazeem** [comment]
@liquidaty: Was this reported by any other users or experienced internally?
I was planning to work on it by building on Ubuntu 18.04 container.
But, if it's not an issue, this can simply be closed.
