### ISSUE TITLE
Incorrect column count on last row with empty column

### ISSUE THREAD

**Issue by woollybah** [liquidaty/zsv#91]
It appears that zsv produces an incorrect column count on the last row if the last column is empty and an EOL (end-of-line) is not provided.

The following csv does not have an EOL on the final row. This should not affect the number of columns reported by the library, but it does. In this case, only a single column is reported on the last row - whereas it correctly reports 2 columns on the preceding row.
```
one,two
1,2
3,
4,
```

This is the result of `pull.c` on the above.
```
Row 1 has 2 columns of which 2 are non-blank
Row 2 has 2 columns of which 2 are non-blank
Row 3 has 2 columns of which 1 is non-blank
Row 4 has 1 columns of which 1 is non-blank
```
As you can see, it incorrectly reports the last row as having only 1 column.

Adding an EOL to the last row produces a different result, with the last row now reporting 2 columns :
```
one,two
1,2
3,
4,

```
This is the result of `pull.c` with the EOL added to the last row :
```
Row 1 has 2 columns of which 2 are non-blank
Row 2 has 2 columns of which 2 are non-blank
Row 3 has 2 columns of which 1 is non-blank
Row 4 has 2 columns of which 1 is non-blank
```

**Comment by liquidaty** [comment]
Thank you for finding and reporting this bug. I believe it has now been fixed (and related tests added) to the branch no-eol-bug (https://github.com/liquidaty/zsv/tree/no-eol-bug). If you get a chance to do so, could you try that one out and confirm that it resolves the issue as you understand it?

**Comment by woollybah** [comment]
The issue appears to have been resolved.
Thank you!
