### ISSUE TITLE
choco.exe install failing

### ISSUE THREAD

**Issue by aagha** [liquidaty/zsv#95]
Any idea why this might be failing?

I downloaded the latest `zsv-0.3.4-alpha-amd64-windows-mingw.nupkg` and am executing: 

`choco install zsv -source .\zsv-0.3.4-alpha-amd64-windows-mingw.nupkg`

![image](https://user-images.githubusercontent.com/5522103/209038763-2bef0424-abe4-4ba2-83d3-e6749b739453.png)

**Comment by liquidaty** [comment]
Confirmed this issue has been reproduced. Will update when resolved.

In the meantime, as a workaround could you please try downloading from the below, and placing the bin\zsv.exe file into an appropriate folder in your PATH:?

https://github.com/liquidaty/zsv/releases/tag/v0.3.4-alpha

**Comment by liquidaty** [comment]
Please use `--pre` with choco.exe. Will be sure to update the README. Thank you for reporting this issue!

```
choco.exe install zsv --pre -source .\zsv-0.3.4-alpha-amd64-windows-mingw.nupkg
```

**Comment by aagha** [comment]
@liquidaty Looks liek that worked:

![image](https://user-images.githubusercontent.com/5522103/209210840-f08f76ef-9472-47b3-9a18-02320601ec47.png)
